# Generated by Django 2.0.4 on 2018-08-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='UserToken',
        ),
    ]
