# Generated by Django 2.0.4 on 2018-09-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20180909_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('1', '未审核'), ('2', '审核中'), ('3', '已发布')], default=1, max_length=4),
        ),
    ]
